openapi: 3.0.3
info:
  title: Trip Tour - OpenAPI 3.0
  description: Trabajo de fin de grado Ingenieria Multimedia realizado por Javier
    Sirvent Mancheño
  contact:
    email: javisirvent2001@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:8080
tags:
- name: Usuario
  description: Llamadas a Usuario
- name: Destino
  description: LLamadas a Destino
- name: Ruta
  description: LLamadas a Ruta
- name: PuntosRuta
  description: LLamadas a PuntosRuta
- name: Logs
  description: LLamadas a Logs
- name: Comentarios
  description: LLamadas a Comentarios
paths:
  /api/usuario:
    get:
      tags:
      - Usuario
      summary: Obtener todos los usuarios
      description: Obtener todos los usuarios
      operationId: getListaUsuarios
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetListaUsuarios'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Usuario
    post:
      tags:
      - Usuario
      summary: Crear un nuevo usuario
      description: Crear un nuevo usuario
      operationId: postUsuario
      requestBody:
        description: Usuario creado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Usuario
  /api/usuario{id}:
    get:
      tags:
      - Usuario
      summary: Obtener todos los usuarios
      description: Obtener todos los usuarios
      operationId: getUsuario
      parameters:
      - name: id
        in: path
        description: ID del usuario
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Usuario
    put:
      tags:
      - Usuario
      summary: Editar usuario existente
      description: Editar usuario existente
      operationId: putUsuario
      parameters:
      - name: id
        in: path
        description: ID del usuario
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Usuario actualizado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Usuario
    delete:
      tags:
      - Usuario
      summary: Eliminar usuario existente
      description: Eliminar usuario existente
      operationId: deleteUsuario
      parameters:
      - name: id
        in: path
        description: ID del usuario
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Usuario
  /api/destino:
    get:
      tags:
      - Destino
      summary: Obtener todos los destinos
      description: Obtener todos los destinos
      operationId: getListaDestinos
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetListaDestinos'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Destino
    post:
      tags:
      - Destino
      summary: Crear un nuevo destino
      description: Crear un nuevo destino
      operationId: postDestino
      requestBody:
        description: Destino creado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Destino'
        required: true
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destino'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Destino
  /api/destino{id}:
    get:
      tags:
      - Destino
      summary: Obtener destino por ID
      description: Obtener destino por ID
      operationId: getDestino
      parameters:
      - name: id
        in: path
        description: ID del destino
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destino'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Destino
    put:
      tags:
      - Destino
      summary: Editar destino existente
      description: Editar destino existente
      operationId: putDestino
      parameters:
      - name: id
        in: path
        description: ID del destino
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Destino actualizado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Destino'
        required: true
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destino'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Destino
    delete:
      tags:
      - Destino
      summary: Eliminar un destino
      description: Eliminar un destino
      operationId: deleteDestino
      parameters:
      - name: id
        in: path
        description: ID del destino
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destino'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Destino
  /api/ruta:
    get:
      tags:
      - Ruta
      summary: Obtener todas las rutas
      description: Obtener todas las rutas
      operationId: getListaRutas
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetListaRutas'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Ruta
    post:
      tags:
      - Ruta
      summary: Crear una nueva ruta
      description: Crear una nueva ruta
      operationId: postRuta
      requestBody:
        description: Destino creado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ruta'
        required: true
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ruta'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Ruta
  /api/ruta{id}:
    get:
      tags:
      - Ruta
      summary: Obtener ruta por ID
      description: Obtener ruta por ID
      operationId: getRuta
      parameters:
      - name: id
        in: path
        description: ID de la ruta
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ruta'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Ruta
    put:
      tags:
      - Ruta
      summary: Editar ruta existente
      description: Editar ruta existente
      operationId: putRuta
      parameters:
      - name: id
        in: path
        description: ID de la ruta
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Ruta actualizada
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ruta'
        required: true
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ruta'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Ruta
    delete:
      tags:
      - Ruta
      summary: Eliminar una ruta
      description: Eliminar una ruta
      operationId: deleteRuta
      parameters:
      - name: id
        in: path
        description: ID de la ruta
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ruta'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Ruta
  /api/puntosruta:
    get:
      tags:
      - PuntosRuta
      summary: Obtener todos los destinos de todas las rutas
      description: Obtener todos los destinos de todas las rutas
      operationId: getListaPuntosRutas
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetListaPuntosRuta'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: PuntosRuta
    post:
      tags:
      - PuntosRuta
      summary: Añadir un punto de ruta
      description: Añadir un punto de ruta
      operationId: postPuntosRuta
      requestBody:
        description: PuntoRuta Creado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PuntosRuta'
        required: true
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PuntosRuta'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: PuntosRuta
  /api/puntosruta{ruta_id}:
    get:
      tags:
      - PuntosRuta
      summary: Obtener todos los destinos de una ruta específica
      description: Obtener todos los destinos de una ruta específica
      operationId: getPuntosRuta
      parameters:
      - name: ruta_id
        in: path
        description: ID de la ruta
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetListaPuntosRuta'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: PuntosRuta
  /api/puntosruta{id}:
    delete:
      tags:
      - PuntosRuta
      summary: Eliminar un destino de una ruta
      description: Eliminar un destino de una ruta
      operationId: deletePuntosRuta
      parameters:
      - name: id
        in: path
        description: ID de la ruta
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PuntosRuta'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: PuntosRuta
  /api/logs:
    get:
      tags:
      - Logs
      summary: Obtener todas las acciones realizadas por los usuarios en el sistema
      description: Obtener todas las acciones realizadas por los usuarios en el sistema
      operationId: getListaLogs
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetListaLogs'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Logs
    post:
      tags:
      - Logs
      summary: Añadir un log
      description: Añadir un log
      operationId: postLogs
      requestBody:
        description: Log añadido
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Log'
        required: true
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Log'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Logs
  /api/comentarios:
    post:
      tags:
      - Comentarios
      summary: Añadir un comentario
      description: Añadir un comentario
      operationId: postComentario
      requestBody:
        description: Comentario añadido
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comentarios'
        required: true
      responses:
        "200":
          description: Operación realizada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comentarios'
        "400":
          description: Imposible realizar la operación en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorRespuesta400'
      x-swagger-router-controller: Comentarios
components:
  schemas:
    Usuario:
      type: object
      properties:
        idUsuarios:
          type: string
          example: 1eq4237efv6g7l44l3
        nombre_usuario:
          type: string
          example: javier45
        nombre:
          type: string
          example: Javier
        apellidos:
          type: string
          example: Sirvent Mancheño
        correo:
          type: string
          example: correo@gmail.com
        contra:
          type: string
        rol:
          type: string
          example: rol_admin
        fecha_nacimiento:
          type: string
          format: date
          example: 2000-10-10
        imagen:
          type: string
      example:
        apellidos: Sirvent Mancheño
        correo: correo@gmail.com
        fecha_nacimiento: 2017-09-09
        imagen: imagen
        nombre_usuario: javier45
        nombre: Javier
        idUsuarios: 1eq4237efv6g7l44l3
        contra: contra
        rol: rol_admin
    Destino:
      type: object
      properties:
        idRuta:
          type: string
          example: 1eq4237efv6g7l44l3
        nombre:
          type: string
          example: Sagrada Familia
        descripcion:
          type: string
          example: Monumento emblematico de la ciudad condal
        localizacion:
          type: string
          example: Barcelona
        categoria:
          type: string
          example: Cultural
        precio:
          type: integer
          format: int64
          example: 0
        imagen:
          type: string
        Dia:
          type: string
          format: date
          example: 2023-05-09
        Hora:
          type: string
          format: date
          example: 2017-07-21 17:32:28
      example:
        descripcion: Monumento emblematico de la ciudad condal
        precio: 0
        Hora: 12:00
        categoria: Cultural
        localizacion: Barcelona
        imagen: imagen
        nombre: Sagrada Familia
        Dia: 2023-05-09T00:00:00.000+00:00
        idRuta: 1eq4237efv6g7l44l3
    Ruta:
      type: object
      properties:
        idRuta:
          type: string
          example: 1eq4237efv6g7l44l3
        nombre:
          type: string
          example: Ruta barcelona
        descripcion:
          type: string
          example: Ruta para recorrer con tu familia/amigos durante unos dias
        fecha_inicio:
          type: string
          format: date
          example: 2023-05-10
        fecha_final:
          type: string
          format: date
          example: 2023-05-13
      example:
        descripcion: Ruta para recorrer con tu familia/amigos durante unos dias
        fecha_inicio: 2023-05-10T00:00:00.000+00:00
        fecha_final: 2023-05-13T00:00:00.000+00:00
        nombre: Ruta barcelona
        idRuta: 1eq4237efv6g7l44l3
    PuntosRuta:
      type: object
      properties:
        idPuntosRuta:
          type: integer
          format: int64
          example: 10
        idRuta:
          type: string
          example: 1eq4237efv6g7l44l3
        idDestino:
          type: string
          example: 1eq4237efv6g7l44l3
      example:
        idPuntosRuta: 10
        idRuta: 1eq4237efv6g7l44l3
        idDestino: 1eq4237efv6g7l44l3
    Log:
      type: object
      properties:
        idlogs:
          type: string
          example: 1eq4237efv6g7l44l3
        tipo:
          type: string
          example: informativo
        idUsuario:
          type: string
          example: 1eq4237efv6g7l44l3
        accion:
          type: string
          example: Iniciar Sesion
        descripcion:
          type: string
          example: El usuario javier45 ha iniciado sesion
        fecha:
          type: string
          format: date
          example: 2023-05-10
      example:
        accion: Iniciar Sesion
        descripcion: El usuario javier45 ha iniciado sesion
        fecha: 2023-05-10T00:00:00.000+00:00
        tipo: informativo
        idUsuario: 1eq4237efv6g7l44l3
        idlogs: 1eq4237efv6g7l44l3
    Comentarios:
      type: object
      properties:
        idComentarios:
          type: string
          example: 1eq4237efv6g7l44l3
        idUsuario:
          type: string
          example: 1eq4237efv6g7l44l3
        mensaje:
          type: string
          example: Me gusta mucho esta ruta
        fecha:
          type: string
          format: date
          example: 2023-05-10
        idRuta:
          type: string
          example: 1eq4237efv6g7l44l3
        valoracion:
          type: integer
          format: int64
          example: 4
      example:
        fecha: 2023-05-10T00:00:00.000+00:00
        idUsuario: 1eq4237efv6g7l44l3
        valoracion: 4
        mensaje: Me gusta mucho esta ruta
        idComentarios: 1eq4237efv6g7l44l3
        idRuta: 1eq4237efv6g7l44l3
    Usuarios:
      type: array
      items:
        $ref: '#/components/schemas/Usuario'
    GetListaUsuarios:
      type: object
      properties:
        res:
          type: string
        obj:
          $ref: '#/components/schemas/Usuarios'
      example:
        res: res
        obj:
        - apellidos: Sirvent Mancheño
          correo: correo@gmail.com
          fecha_nacimiento: 2000-10-10T00:00:00.000+00:00
          imagen: imagen
          nombre_usuario: javier45
          nombre: Javier
          idUsuarios: 1eq4237efv6g7l44l3
          contra: contra
          rol: rol_admin
        - apellidos: Sirvent Mancheño
          correo: correo@gmail.com
          fecha_nacimiento: 2000-10-10T00:00:00.000+00:00
          imagen: imagen
          nombre_usuario: javier45
          nombre: Javier
          idUsuarios: 1eq4237efv6g7l44l3
          contra: contra
          rol: rol_admin
    Destinos:
      type: array
      items:
        $ref: '#/components/schemas/Destino'
    GetListaDestinos:
      type: object
      properties:
        res:
          type: string
        obj:
          $ref: '#/components/schemas/Destinos'
      example:
        res: res
        obj:
        - descripcion: Monumento emblematico de la ciudad condal
          precio: 0
          Hora: 12:00
          categoria: Cultural
          localizacion: Barcelona
          imagen: imagen
          nombre: Sagrada Familia
          Dia: 2023-05-09T00:00:00.000+00:00
          idRuta: 1eq4237efv6g7l44l3
        - descripcion: Monumento emblematico de la ciudad condal
          precio: 0
          Hora: 12:00
          categoria: Cultural
          localizacion: Barcelona
          imagen: imagen
          nombre: Sagrada Familia
          Dia: 2023-05-09T00:00:00.000+00:00
          idRuta: 1eq4237efv6g7l44l3
    Rutas:
      type: array
      items:
        $ref: '#/components/schemas/Ruta'
    GetListaRutas:
      type: object
      properties:
        res:
          type: string
        obj:
          $ref: '#/components/schemas/Rutas'
      example:
        res: res
        obj:
        - descripcion: Ruta para recorrer con tu familia/amigos durante unos dias
          fecha_inicio: 2023-05-10T00:00:00.000+00:00
          fecha_final: 2023-05-13T00:00:00.000+00:00
          nombre: Ruta barcelona
          idRuta: 1eq4237efv6g7l44l3
        - descripcion: Ruta para recorrer con tu familia/amigos durante unos dias
          fecha_inicio: 2023-05-10T00:00:00.000+00:00
          fecha_final: 2023-05-13T00:00:00.000+00:00
          nombre: Ruta barcelona
          idRuta: 1eq4237efv6g7l44l3
    PuntosRutas:
      type: array
      items:
        $ref: '#/components/schemas/PuntosRuta'
    GetListaPuntosRuta:
      type: object
      properties:
        res:
          type: string
        obj:
          $ref: '#/components/schemas/PuntosRutas'
      example:
        res: res
        obj:
        - idPuntosRuta: 10
          idRuta: 1eq4237efv6g7l44l3
          idDestino: 1eq4237efv6g7l44l3
        - idPuntosRuta: 10
          idRuta: 1eq4237efv6g7l44l3
          idDestino: 1eq4237efv6g7l44l3
    Logs:
      type: array
      items:
        $ref: '#/components/schemas/Log'
    GetListaLogs:
      type: object
      properties:
        res:
          type: string
        obj:
          $ref: '#/components/schemas/Logs'
      example:
        res: res
        obj:
        - accion: Iniciar Sesion
          descripcion: El usuario javier45 ha iniciado sesion
          fecha: 2023-05-10T00:00:00.000+00:00
          tipo: informativo
          idUsuario: 1eq4237efv6g7l44l3
          idlogs: 1eq4237efv6g7l44l3
        - accion: Iniciar Sesion
          descripcion: El usuario javier45 ha iniciado sesion
          fecha: 2023-05-10T00:00:00.000+00:00
          tipo: informativo
          idUsuario: 1eq4237efv6g7l44l3
          idlogs: 1eq4237efv6g7l44l3
    errorRespuesta400:
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
